#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AssessmentWeatherApp.Resource", IsApplication=true)]

namespace AssessmentWeatherApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int auckland = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int backgroundday = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int backgrounddusk = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int backgroundnight = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int christchurch = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int hamilton = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int monoandroidsplash = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int NZWeather = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int temperaturehigh = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int temperaturelow = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int weatherclear = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int weatherclearnight = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int weatherclouds = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int weathercloudsnight = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int weatherfewclouds = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int weatherfewcloudsnight = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int weatherfog = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int weatherhail = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int weatherhazy = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int weathermanyclouds = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int weathershowers = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int weathershowersday = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int weathershowersnight = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int weathershowersscattered = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int weathershowersscatteredday = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int weathershowersscatterednight = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int weathersnow = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int weathersnowrain = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int weathersnowscattered = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int weathersnowscatteredday = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int weathersnowscatterednight = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int weatherstorm = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int weatherstormday = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int weatherstormnight = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int weatherunknown = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int wellington = 2130837540;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int btnAuckland = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int btnChristchurch = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int btnHamilton = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int btnWellington = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int imgCondNow = 2131099657;
			
			// aapt resource value: 0x7f060025
			public const int imgDay1 = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int imgDay2 = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int imgDay3 = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int imgDay4 = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int imgDay5 = 2131099689;
			
			// aapt resource value: 0x7f060016
			public const int ivMaxTemp = 2131099670;
			
			// aapt resource value: 0x7f06001d
			public const int ivMinTemp = 2131099677;
			
			// aapt resource value: 0x7f060007
			public const int linearLayout1 = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int linearLayout2 = 2131099658;
			
			// aapt resource value: 0x7f060004
			public const int llBackground = 2131099652;
			
			// aapt resource value: 0x7f06000d
			public const int tableLayout1 = 2131099661;
			
			// aapt resource value: 0x7f060023
			public const int trConditions = 2131099683;
			
			// aapt resource value: 0x7f06000e
			public const int trDays = 2131099662;
			
			// aapt resource value: 0x7f060015
			public const int trMaxTemp = 2131099669;
			
			// aapt resource value: 0x7f06001c
			public const int trMinTemp = 2131099676;
			
			// aapt resource value: 0x7f06000f
			public const int tvDays = 2131099663;
			
			// aapt resource value: 0x7f060005
			public const int txtCityName = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int txtCondNow = 2131099659;
			
			// aapt resource value: 0x7f060024
			public const int txtConditions = 2131099684;
			
			// aapt resource value: 0x7f060006
			public const int txtDateNow = 2131099654;
			
			// aapt resource value: 0x7f060010
			public const int txtDay1 = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int txtDay2 = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int txtDay3 = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int txtDay4 = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int txtDay5 = 2131099668;
			
			// aapt resource value: 0x7f060017
			public const int txtMax1 = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int txtMax2 = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int txtMax3 = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int txtMax4 = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int txtMax5 = 2131099675;
			
			// aapt resource value: 0x7f06000c
			public const int txtMaxMinNow = 2131099660;
			
			// aapt resource value: 0x7f06001e
			public const int txtMin1 = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int txtMin2 = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int txtMin3 = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int txtMin4 = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int txtMin5 = 2131099682;
			
			// aapt resource value: 0x7f060008
			public const int txtTempNow = 2131099656;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ChangeCity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Weather = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int Mono_Android_Theme_Splash = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
